#define CLK_HALF_PERIOD             10
#define SCK_HALF_PERIOD             50

#define SPI_RO_STAGE_SEL            0
#define SPI_GET_CLKINT_OUT          0

#define SPI_RST_MODE                0
#define SPI_DO_EPROP                0
#define SPI_LOCAL_TICK              0
#define SPI_ERROR_HALT              1
#define SPI_FP_LOC_WINP             3
#define SPI_FP_LOC_WREC             3
#define SPI_FP_LOC_WOUT             3
#define SPI_FP_LOC_TINP             3
#define SPI_FP_LOC_TREC             4
#define SPI_FP_LOC_TOUT             6
#define SPI_LEARN_SIG_SCALE         5
#define SPI_REGUL_MODE              2
#define SPI_REGUL_W                 3
#define SPI_EN_STOCH_ROUND          1
#define SPI_SRAM_SPEEDMODE          0
#define SPI_TIMING_MODE             0
#define SPI_REGRESSION              0
#define SPI_SINGLE_LABEL            1
#define SPI_NO_OUT_ACT              0
#define SPI_SEND_PER_TIMESTEP       0
#define SPI_SEND_LABEL_ONLY         1
#define SPI_NOISE_EN                0
#define SPI_FORCE_TRACES            0

#define SPI_CYCLES_PER_TICK         0
#define SPI_ALPHA_CONF              0
#define SPI_KAPPA                   0x79
#define SPI_THR_H_0                 205
#define SPI_THR_H_1                 205
#define SPI_THR_H_2                 205
#define SPI_THR_H_3                 205
#define SPI_H_0                     0
#define SPI_H_1                     0
#define SPI_H_2                     0
#define SPI_H_3                     0
#define SPI_H_4                     1
#define SPI_LR_R_WINP               0 
#define SPI_LR_P_WINP               8
#define SPI_LR_R_WREC               0
#define SPI_LR_P_WREC               8
#define SPI_LR_R_WOUT               0
#define SPI_LR_P_WOUT               14
#define SPI_SEED_INP                0xF0F0
#define SPI_SEED_REC                0xF1F1
#define SPI_SEED_OUT                0xF2F2
#define SPI_SEED_STRND_NEUR         0x3F3FF3F3
#define SPI_SEED_STRND_ONEUR        0xF4F4
#define SPI_SEED_STRND_TINP         0x3F5FF5F5
#define SPI_SEED_STRND_TREC         0x3F6FF6F6
#define SPI_SEED_STRND_TOUT         0x3F7FF7F7
#define SPI_SEED_NOISE_NEUR         0x00FF0
#define SPI_NUM_INP_NEUR            39
#define SPI_NUM_REC_NEUR            99
#define SPI_NUM_OUT_NEUR            1
#define SPI_REGUL_F0                160
#define SPI_REGUL_K_INP_R           0
#define SPI_REGUL_K_INP_P           10
#define SPI_REGUL_K_REC_R           0
#define SPI_REGUL_K_REC_P           10
#define SPI_REGUL_K_MUL             0
#define SPI_NOISE_STR               0000
